apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: hc6scibml-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/hc6scibml-java-springboot-gitops